#!/bin/sh

pwd=$(pwd)
cd $(dirname $0)/../lib
db=$(basename $(dirname $(pwd)))
mkdir -p Schema/Result Schema/ResultSet
dbicdump -o dump_directory=. -o default_resultset_class=ResultSet -o result_base_class='Schema::Result' -o components='["InflateColumn::DateTime", "Helper::Row::ToJSON"]' -o preserve_case=1 Schema dbi:mysql:database=${1:-$db} ${2:-$db} ${3:-$db} '{ quote_char => "`" }'
