#!/bin/sh

pwd=$(pwd)
cd $(dirname $0)
dbicdump -o dump_directory=../lib -o components='["InflateColumn::DateTime"]' -o preserve_case=1 Schema dbi:mysql:database=velite velite velite '{ quote_char => "`" }'
cd $pwd
